apiVersion: v1
kind: Namespace
metadata:
  name: data
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres
  namespace: data
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
  namespace: data
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      serviceAccountName: postgres
      containers:
      - name: postgres
        image: tufinim/postgres
        ports:
        - containerPort: 8088
