apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: default
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
  - name: http
    port: 5432
    targetPort: 5432
    protocol: TCP
  type: ClusterIP