version: "3"

services:

  redis:
    image: redis:3.2-alpine
    ports:
      - "6379"
    networks:
      - boanet

  app-server:
    image: tufinim/bank-of-america
    environment:
      - REDIS=redis:6379
    ports:
      - 8085:8085
    networks:
      - boanet
    depends_on:
      - postgres
    deploy:
      mode: replicated
      replicas: 1
      labels: [APP=BANK]

networks:
    boanet:

volumes:
  db-data: