version: "3"

services:

  redis:
    image: redis:3.2-alpine
    ports:
      - "6379"
    networks:
      - boanet
    deploy:
      placement:
        constraints: [node.role == manager]

  db:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=admin
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - boanet
    deploy:
      placement:
        constraints: [node.role == manager]

  bank:
    build: .
    environment:
      - REDIS=redis:6379
    ports:
      - 80:8085
    networks:
      - boanet
    depends_on:
      - redis
      - db
    deploy:
      mode: replicated
      replicas: 2
      labels: [APP=BANK]
      placement:
        constraints: [node.role == worker]

networks:
    boanet:

volumes:
  db-data: