apiVersion: v1
kind: ServiceAccount
metadata:
  name: indexer
  namespace: default
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: indexer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: indexer
    spec:
      serviceAccountName: indexer
      containers:
      - name: indexer
        image: tufinim/generic-bank-indexer
        env:
        - name: REDIS
          value: "http://redis"
        - name: POSTGRES
          value: "http://postgres"
        - name: POSTGRES_USER
          value: "admin"
        - name: POSTGRES_PASSWORD
          value: "123"
