version: 2.1
executors:
  service_exec:
    working_directory: /go/src/github.com/tufin/generic-bank
    docker:
      - image: tufinim/circleci-go:master
commands:
  build_and_push:
    description: "Build docker image and push to registry"
    parameters:
      service:
        type: string
    steps:
      - setup_remote_docker
      - run:
          name: Build docker image and push to registry
          command: |
            cd db
            src="<< parameters.service >>"
            docker build --build-arg SERVICE="${src}" -t "${src}" .
            echo ${DOCKER_PASS} | docker login -u ${DOCKER_USER} --password-stdin
            target="tufinim/<< parameters.service >>"
            docker tag "${src}" "${target}"
            docker tag "${src}" "${target}:${CIRCLE_BRANCH}"
            docker tag "${src}" "${target}:${CIRCLE_BUILD_NUM}"
            docker tag "${src}" "${target}:${CIRCLE_BUILD_NUM}-${CIRCLE_BRANCH}"
            docker push "${target}"
jobs:
  build:
    executor: service_exec
    environment:
      IMAGE_NAME: tufinim/generic-bank
      TUFIN_DOMAIN: generic-bank
      TUFIN_PROJECT: retail
      TUFIN_URL: https://securecloud.tufin.io
      TUFIN_HOST: securecloud.tufin.io
    steps:
      - checkout
      - run:
          name: Fetch latest UI from Tufin/generic-bank-ui releases
          command: |
            mkdir ui
            curl -o ui.zip `curl -i -H "Accept: application/octet-stream" -H "Authorization: token $GITHUB_TOKEN" $(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/Tufin/generic-bank-ui/releases/latest | grep url | grep releases\/assets | egrep -o "https://[^\"]+") | grep location: | cut -d " " -f2 | tr -d '\r\n'` && echo 'ignore cache'
            unzip ui.zip -d ./ui
      - run:
          name: Build
          command: |
            go get -v -t -d ./...
            mkdir ".dist"
            CGO_ENABLED=0 go build -v -o ".dist/generic-bank"
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t "$IMAGE_NAME" .
      - run:
          name: Upload docker image to dockerhub
          command: |
            docker tag $IMAGE_NAME $IMAGE_NAME:$CIRCLE_BUILD_NUM
            echo "$DOCKER_PASS" | docker login -u $DOCKER_USER --password-stdin
            docker push $IMAGE_NAME
      - run:
          name: Tufin image analysis
          command: |
            export TUFIN_API_KEY=$GENERIC_BANK_RETAIL_ALL_TOKEN
            export TUFIN_DOCKER_REPO_PASSWORD=$GENERIC_BANK_RETAIL_AGENT_TOKEN
            url="$TUFIN_URL/api/scripts/image-scan"
            echo $url
            bash <(curl -s $url) "$IMAGE_NAME:$CIRCLE_BUILD_NUM"
      - run:
          name: Authenticate with gcloud
          command:
            echo $GCLOUD_SERVICE_KEY | /scripts/gcloud_auth.sh
      - run:
          name: Update deployment on google cloud (if tufin.io cluster is up and running)
          command: |
            /scripts/update_deployment.sh $GCLOUD_PROJECT_ID $GCLOUD_CLUSTER_NAME $GCLOUD_ZONE deployment/$DEPLOYMENT admin=$IMAGE_NAME:$CIRCLE_BUILD_NUM default
          environment:
            GCLOUD_SERVICE_KEY_FILE: gcloud-service-key.json
            GCLOUD_PROJECT_ID: tufin-orca-prod
            GCLOUD_CLUSTER_NAME: aut-generic-bank-retail
            GCLOUD_ZONE: europe-west1-b
            DEPLOYMENT: admin
  db:
    executor: service_exec
    steps:
      - build_and_push:
          service: tufin-db
