general:
  branches:
    ignore:
      - world-trading-updates
version: 2
jobs:
  build:
    working_directory: /go/src/github.com/tufin/generic-bank
    docker:
      - image: tufinim/circleci-go:master
    environment:
      IMAGE_NAME: tufinim/generic-bank
      TUFIN_DOMAIN: generic-bank
      TUFIN_PROJECT: retail
      TUFIN_URL: https://orca.tufin.io
    steps:
      - checkout
      - run:
          name: Build
          command: |
            /scripts/go_build.sh generic-bank
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t "$IMAGE_NAME" .
      - run:
          name: Upload docker image to dockerhub
          command: |
            docker tag $IMAGE_NAME $IMAGE_NAME:$CIRCLE_BUILD_NUM
            echo "$DOCKER_PASS" | docker login -u $DOCKER_USER --password-stdin
            docker push $IMAGE_NAME
      - run:
          name: Tufin image analysis
          command: |
            bash <(curl -H "Authorization: Bearer $TUFIN_API_KEY" -s $TUFIN_URL/api/scripts/image-scan) "$IMAGE_NAME:$CIRCLE_BUILD_NUM"
            echo "$TUFIN_SECURITY_SCORE"
            echo "$TUFIN_SECURITY_SCORE" >> env_file
      - run:
          name: Tufin Continuous Security Policy
          command: |
            source env_file
            echo "$TUFIN_SECURITY_SCORE"
            bash <(curl -H "Authorization: Bearer $TUFIN_API_KEY" -s $TUFIN_URL/lighthouse/$TUFIN_DOMAIN/$TUFIN_PROJECT/bash) policy.yaml
          environment:
            TUFIN_ALLOW_ACCESS_SERVICE: admin
      - run:
          name: Authenticate with gcloud
          command:
            echo $GCLOUD_SERVICE_KEY | /scripts/gcloud_auth.sh
      - run:
          name: Update deployment on google cloud (if tufin.io cluster is up and running)
          command: |
            /scripts/update_deployment.sh $GCLOUD_PROJECT_ID $GCLOUD_CLUSTER_NAME $GCLOUD_ZONE deployment/$DEPLOYMENT admin=$IMAGE_NAME:$CIRCLE_BUILD_NUM default
          environment:
            GCLOUD_SERVICE_KEY_FILE: gcloud-service-key.json
            GCLOUD_PROJECT_ID: dream-198012
            GCLOUD_CLUSTER_NAME: aut-cluster
            GCLOUD_ZONE: europe-west1-b
            DEPLOYMENT: admin
